package mods.Hileb.optirefine.optifine.client;

import mods.Hileb.optirefine.optifine.Config;
import net.minecraft.client.settings.GameSettings;
import net.minecraftforge.common.util.EnumHelper;

@SuppressWarnings("unused")
public class GameSettingsOptionOF {
    private static final Class<?>[] args0 = new Class[]{String.class, boolean.class, boolean.class};
    private static final Class<?>[] args1 = new Class[]{String.class, boolean.class, boolean.class, float.class, float.class, float.class};
    
    public static final GameSettings.Options FOG_FANCY = EnumHelper.addEnum(GameSettings.Options.class, "FOG_FANCY", args0, "of.options.FOG_FANCY", false, false);
    public static final GameSettings.Options FOG_START = EnumHelper.addEnum(GameSettings.Options.class, "FOG_START", args0, "of.options.FOG_START", false, false);
    public static final GameSettings.Options MIPMAP_TYPE = EnumHelper.addEnum(GameSettings.Options.class, "MIPMAP_TYPE", args1, "of.options.MIPMAP_TYPE", true, false, 0.0F, 3.0F, 1.0F);
    public static final GameSettings.Options SMOOTH_FPS = EnumHelper.addEnum(GameSettings.Options.class, "SMOOTH_FPS", args0, "of.options.SMOOTH_FPS", false, false);
    public static final GameSettings.Options CLOUDS = EnumHelper.addEnum(GameSettings.Options.class, "CLOUDS", args0, "of.options.CLOUDS", false, false);
    public static final GameSettings.Options CLOUD_HEIGHT = EnumHelper.addEnum(GameSettings.Options.class, "CLOUD_HEIGHT", args0, "of.options.CLOUD_HEIGHT", true, false);
    public static final GameSettings.Options TREES = EnumHelper.addEnum(GameSettings.Options.class, "TREES", args0, "of.options.TREES", false, false);
    public static final GameSettings.Options RAIN = EnumHelper.addEnum(GameSettings.Options.class, "RAIN", args0, "of.options.RAIN", false, false);
    public static final GameSettings.Options ANIMATED_WATER = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_WATER", args0, "of.options.ANIMATED_WATER", false, false);
    public static final GameSettings.Options ANIMATED_LAVA = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_LAVA", args0, "of.options.ANIMATED_LAVA", false, false);
    public static final GameSettings.Options ANIMATED_FIRE = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_FIRE", args0, "of.options.ANIMATED_FIRE", false, false);
    public static final GameSettings.Options ANIMATED_PORTAL = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_PORTAL", args0, "of.options.ANIMATED_PORTAL", false, false);
    public static final GameSettings.Options AO_LEVEL = EnumHelper.addEnum(GameSettings.Options.class, "AO_LEVEL", args0, "of.options.AO_LEVEL", true, false);
    public static final GameSettings.Options LAGOMETER = EnumHelper.addEnum(GameSettings.Options.class, "LAGOMETER", args0, "of.options.LAGOMETER", false, false);
    public static final GameSettings.Options SHOW_FPS = EnumHelper.addEnum(GameSettings.Options.class, "SHOW_FPS", args0, "of.options.SHOW_FPS", false, false);
    public static final GameSettings.Options AUTOSAVE_TICKS = EnumHelper.addEnum(GameSettings.Options.class, "AUTOSAVE_TICKS", args0, "of.options.AUTOSAVE_TICKS", false, false);
    public static final GameSettings.Options BETTER_GRASS = EnumHelper.addEnum(GameSettings.Options.class, "BETTER_GRASS", args0, "of.options.BETTER_GRASS", false, false);
    public static final GameSettings.Options ANIMATED_REDSTONE = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_REDSTONE", args0, "of.options.ANIMATED_REDSTONE", false, false);
    public static final GameSettings.Options ANIMATED_EXPLOSION = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_EXPLOSION", args0, "of.options.ANIMATED_EXPLOSION", false, false);
    public static final GameSettings.Options ANIMATED_FLAME = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_FLAME", args0, "of.options.ANIMATED_FLAME", false, false);
    public static final GameSettings.Options ANIMATED_SMOKE = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_SMOKE", args0, "of.options.ANIMATED_SMOKE", false, false);
    public static final GameSettings.Options WEATHER = EnumHelper.addEnum(GameSettings.Options.class, "WEATHER", args0, "of.options.WEATHER", false, false);
    public static final GameSettings.Options SKY = EnumHelper.addEnum(GameSettings.Options.class, "SKY", args0, "of.options.SKY", false, false);
    public static final GameSettings.Options STARS = EnumHelper.addEnum(GameSettings.Options.class, "STARS", args0, "of.options.STARS", false, false);
    public static final GameSettings.Options SUN_MOON = EnumHelper.addEnum(GameSettings.Options.class, "SUN_MOON", args0, "of.options.SUN_MOON", false, false);
    public static final GameSettings.Options VIGNETTE = EnumHelper.addEnum(GameSettings.Options.class, "VIGNETTE", args0, "of.options.VIGNETTE", false, false);
    public static final GameSettings.Options CHUNK_UPDATES = EnumHelper.addEnum(GameSettings.Options.class, "CHUNK_UPDATES", args0, "of.options.CHUNK_UPDATES", false, false);
    public static final GameSettings.Options CHUNK_UPDATES_DYNAMIC = EnumHelper.addEnum(GameSettings.Options.class, "CHUNK_UPDATES_DYNAMIC", args0, "of.options.CHUNK_UPDATES_DYNAMIC", false, false);
    public static final GameSettings.Options TIME = EnumHelper.addEnum(GameSettings.Options.class, "TIME", args0, "of.options.TIME", false, false);
    public static final GameSettings.Options CLEAR_WATER = EnumHelper.addEnum(GameSettings.Options.class, "CLEAR_WATER", args0, "of.options.CLEAR_WATER", false, false);
    public static final GameSettings.Options SMOOTH_WORLD = EnumHelper.addEnum(GameSettings.Options.class, "SMOOTH_WORLD", args0, "of.options.SMOOTH_WORLD", false, false);
    public static final GameSettings.Options VOID_PARTICLES = EnumHelper.addEnum(GameSettings.Options.class, "VOID_PARTICLES", args0, "of.options.VOID_PARTICLES", false, false);
    public static final GameSettings.Options WATER_PARTICLES = EnumHelper.addEnum(GameSettings.Options.class, "WATER_PARTICLES", args0, "of.options.WATER_PARTICLES", false, false);
    public static final GameSettings.Options RAIN_SPLASH = EnumHelper.addEnum(GameSettings.Options.class, "RAIN_SPLASH", args0, "of.options.RAIN_SPLASH", false, false);
    public static final GameSettings.Options PORTAL_PARTICLES = EnumHelper.addEnum(GameSettings.Options.class, "PORTAL_PARTICLES", args0, "of.options.PORTAL_PARTICLES", false, false);
    public static final GameSettings.Options POTION_PARTICLES = EnumHelper.addEnum(GameSettings.Options.class, "POTION_PARTICLES", args0, "of.options.POTION_PARTICLES", false, false);
    public static final GameSettings.Options FIREWORK_PARTICLES = EnumHelper.addEnum(GameSettings.Options.class, "FIREWORK_PARTICLES", args0, "of.options.FIREWORK_PARTICLES", false, false);
    public static final GameSettings.Options PROFILER = EnumHelper.addEnum(GameSettings.Options.class, "PROFILER", args0, "of.options.PROFILER", false, false);
    public static final GameSettings.Options DRIPPING_WATER_LAVA = EnumHelper.addEnum(GameSettings.Options.class, "DRIPPING_WATER_LAVA", args0, "of.options.DRIPPING_WATER_LAVA", false, false);
    public static final GameSettings.Options BETTER_SNOW = EnumHelper.addEnum(GameSettings.Options.class, "BETTER_SNOW", args0, "of.options.BETTER_SNOW", false, false);
    public static final GameSettings.Options FULLSCREEN_MODE = EnumHelper.addEnum(GameSettings.Options.class, "FULLSCREEN_MODE", args2, "of.options.FULLSCREEN_MODE", true, false, 0.0F, (float) Config.getDisplayModes().length, 1.0F);
    public static final GameSettings.Options ANIMATED_TERRAIN = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_TERRAIN", args0, "of.options.ANIMATED_TERRAIN", false, false);
    public static final GameSettings.Options SWAMP_COLORS = EnumHelper.addEnum(GameSettings.Options.class, "SWAMP_COLORS", args0, "of.options.SWAMP_COLORS", false, false);
    public static final GameSettings.Options RANDOM_ENTITIES = EnumHelper.addEnum(GameSettings.Options.class, "RANDOM_ENTITIES", args0, "of.options.RANDOM_ENTITIES", false, false);
    public static final GameSettings.Options SMOOTH_BIOMES = EnumHelper.addEnum(GameSettings.Options.class, "SMOOTH_BIOMES", args0, "of.options.SMOOTH_BIOMES", false, false);
    public static final GameSettings.Options CUSTOM_FONTS = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_FONTS", args0, "of.options.CUSTOM_FONTS", false, false);
    public static final GameSettings.Options CUSTOM_COLORS = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_COLORS", args0, "of.options.CUSTOM_COLORS", false, false);
    public static final GameSettings.Options SHOW_CAPES = EnumHelper.addEnum(GameSettings.Options.class, "", args0, "of.options.SHOW_CAPES", false, false);
    public static final GameSettings.Options CONNECTED_TEXTURES = EnumHelper.addEnum(GameSettings.Options.class, "CONNECTED_TEXTURES", args0, "of.options.CONNECTED_TEXTURES", false, false);
    public static final GameSettings.Options CUSTOM_ITEMS = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_ITEMS", args0, "of.options.CUSTOM_ITEMS", false, false);
    public static final GameSettings.Options AA_LEVEL = EnumHelper.addEnum(GameSettings.Options.class, "AA_LEVEL", args1, "of.options.AA_LEVEL", true, false, 0.0F, 16.0F, 1.0F);
    public static final GameSettings.Options AF_LEVEL = EnumHelper.addEnum(GameSettings.Options.class, "AF_LEVEL", args1, "of.options.AF_LEVEL", true, false, 1.0F, 16.0F, 1.0F);
    public static final GameSettings.Options ANIMATED_TEXTURES = EnumHelper.addEnum(GameSettings.Options.class, "ANIMATED_TEXTURES", args0, "of.options.ANIMATED_TEXTURES", false, false);
    public static final GameSettings.Options NATURAL_TEXTURES = EnumHelper.addEnum(GameSettings.Options.class, "NATURAL_TEXTURES", args0, "of.options.NATURAL_TEXTURES", false, false);
    public static final GameSettings.Options EMISSIVE_TEXTURES = EnumHelper.addEnum(GameSettings.Options.class, "EMISSIVE_TEXTURES", args0, "of.options.EMISSIVE_TEXTURES", false, false);
    public static final GameSettings.Options HELD_ITEM_TOOLTIPS = EnumHelper.addEnum(GameSettings.Options.class, "HELD_ITEM_TOOLTIPS", args0, "of.options.HELD_ITEM_TOOLTIPS", false, false);
    public static final GameSettings.Options DROPPED_ITEMS = EnumHelper.addEnum(GameSettings.Options.class, "DROPPED_ITEMS", args0, "of.options.DROPPED_ITEMS", false, false);
    public static final GameSettings.Options LAZY_CHUNK_LOADING = EnumHelper.addEnum(GameSettings.Options.class, "LAZY_CHUNK_LOADING", args0, "of.options.LAZY_CHUNK_LOADING", false, false);
    public static final GameSettings.Options CUSTOM_SKY = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_SKY", args0, "of.options.CUSTOM_SKY", false, false);
    public static final GameSettings.Options FAST_MATH = EnumHelper.addEnum(GameSettings.Options.class, "FAST_MATH", args0, "of.options.FAST_MATH", false, false);
    public static final GameSettings.Options FAST_RENDER = EnumHelper.addEnum(GameSettings.Options.class, "FAST_RENDER", args0, "of.options.FAST_RENDER", false, false);
    public static final GameSettings.Options TRANSLUCENT_BLOCKS = EnumHelper.addEnum(GameSettings.Options.class, "TRANSLUCENT_BLOCKS", args0, "of.options.TRANSLUCENT_BLOCKS", false, false);
    public static final GameSettings.Options DYNAMIC_FOV = EnumHelper.addEnum(GameSettings.Options.class, "DYNAMIC_FOV", args0, "of.options.DYNAMIC_FOV", false, false);
    public static final GameSettings.Options DYNAMIC_LIGHTS = EnumHelper.addEnum(GameSettings.Options.class, "DYNAMIC_LIGHTS", args0, "of.options.DYNAMIC_LIGHTS", false, false);
    public static final GameSettings.Options ALTERNATE_BLOCKS = EnumHelper.addEnum(GameSettings.Options.class, "ALTERNATE_BLOCKS", args0, "of.options.ALTERNATE_BLOCKS", false, false);
    public static final GameSettings.Options CUSTOM_ENTITY_MODELS = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_ENTITY_MODELS", args0, "of.options.CUSTOM_ENTITY_MODELS", false, false);
    public static final GameSettings.Options ADVANCED_TOOLTIPS = EnumHelper.addEnum(GameSettings.Options.class, "ADVANCED_TOOLTIPS", args0, "of.options.ADVANCED_TOOLTIPS", false, false);
    public static final GameSettings.Options SCREENSHOT_SIZE = EnumHelper.addEnum(GameSettings.Options.class, "SCREENSHOT_SIZE", args0, "of.options.SCREENSHOT_SIZE", false, false);
    public static final GameSettings.Options CUSTOM_GUIS = EnumHelper.addEnum(GameSettings.Options.class, "CUSTOM_GUIS", args0, "of.options.CUSTOM_GUIS", false, false);
    public static final GameSettings.Options RENDER_REGIONS = EnumHelper.addEnum(GameSettings.Options.class, "RENDER_REGIONS", args0, "of.options.RENDER_REGIONS", false, false);
    public static final GameSettings.Options SHOW_GL_ERRORS = EnumHelper.addEnum(GameSettings.Options.class, "SHOW_GL_ERRORS", args0, "of.options.SHOW_GL_ERRORS", false, false);
    public static final GameSettings.Options SMART_ANIMATIONS = EnumHelper.addEnum(GameSettings.Options.class, "SMART_ANIMATIONS", args0,"of.options.SMART_ANIMATIONS", false, false);
    
}
