package net.minecraft.util.datafix;

import net.minecraft.block.BlockJukebox;
import net.minecraft.entity.Entity;
import net.minecraft.entity.boss.EntityDragon;
import net.minecraft.entity.boss.EntityWither;
import net.minecraft.entity.item.EntityArmorStand;
import net.minecraft.entity.item.EntityEnderPearl;
import net.minecraft.entity.item.EntityExpBottle;
import net.minecraft.entity.item.EntityFallingBlock;
import net.minecraft.entity.item.EntityFireworkRocket;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.item.EntityItemFrame;
import net.minecraft.entity.item.EntityMinecartChest;
import net.minecraft.entity.item.EntityMinecartCommandBlock;
import net.minecraft.entity.item.EntityMinecartEmpty;
import net.minecraft.entity.item.EntityMinecartFurnace;
import net.minecraft.entity.item.EntityMinecartHopper;
import net.minecraft.entity.item.EntityMinecartMobSpawner;
import net.minecraft.entity.item.EntityMinecartTNT;
import net.minecraft.entity.monster.EntityBlaze;
import net.minecraft.entity.monster.EntityCaveSpider;
import net.minecraft.entity.monster.EntityCreeper;
import net.minecraft.entity.monster.EntityElderGuardian;
import net.minecraft.entity.monster.EntityEnderman;
import net.minecraft.entity.monster.EntityEndermite;
import net.minecraft.entity.monster.EntityEvoker;
import net.minecraft.entity.monster.EntityGhast;
import net.minecraft.entity.monster.EntityGiantZombie;
import net.minecraft.entity.monster.EntityGuardian;
import net.minecraft.entity.monster.EntityHusk;
import net.minecraft.entity.monster.EntityIronGolem;
import net.minecraft.entity.monster.EntityMagmaCube;
import net.minecraft.entity.monster.EntityPigZombie;
import net.minecraft.entity.monster.EntityShulker;
import net.minecraft.entity.monster.EntitySilverfish;
import net.minecraft.entity.monster.EntitySkeleton;
import net.minecraft.entity.monster.EntitySlime;
import net.minecraft.entity.monster.EntitySnowman;
import net.minecraft.entity.monster.EntitySpider;
import net.minecraft.entity.monster.EntityStray;
import net.minecraft.entity.monster.EntityVex;
import net.minecraft.entity.monster.EntityVindicator;
import net.minecraft.entity.monster.EntityWitch;
import net.minecraft.entity.monster.EntityWitherSkeleton;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.entity.monster.EntityZombieVillager;
import net.minecraft.entity.passive.EntityBat;
import net.minecraft.entity.passive.EntityChicken;
import net.minecraft.entity.passive.EntityCow;
import net.minecraft.entity.passive.EntityDonkey;
import net.minecraft.entity.passive.EntityHorse;
import net.minecraft.entity.passive.EntityMooshroom;
import net.minecraft.entity.passive.EntityMule;
import net.minecraft.entity.passive.EntityOcelot;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.entity.passive.EntityRabbit;
import net.minecraft.entity.passive.EntitySheep;
import net.minecraft.entity.passive.EntitySkeletonHorse;
import net.minecraft.entity.passive.EntitySquid;
import net.minecraft.entity.passive.EntityVillager;
import net.minecraft.entity.passive.EntityWolf;
import net.minecraft.entity.passive.EntityZombieHorse;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.entity.projectile.EntityArrow;
import net.minecraft.entity.projectile.EntityDragonFireball;
import net.minecraft.entity.projectile.EntityEgg;
import net.minecraft.entity.projectile.EntityLargeFireball;
import net.minecraft.entity.projectile.EntityPotion;
import net.minecraft.entity.projectile.EntitySmallFireball;
import net.minecraft.entity.projectile.EntitySnowball;
import net.minecraft.entity.projectile.EntitySpectralArrow;
import net.minecraft.entity.projectile.EntityTippedArrow;
import net.minecraft.entity.projectile.EntityWitherSkull;
import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.nbt.NBTTagList;
import net.minecraft.tileentity.TileEntityBrewingStand;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.tileentity.TileEntityDispenser;
import net.minecraft.tileentity.TileEntityDropper;
import net.minecraft.tileentity.TileEntityFlowerPot;
import net.minecraft.tileentity.TileEntityFurnace;
import net.minecraft.tileentity.TileEntityHopper;
import net.minecraft.tileentity.TileEntityMobSpawner;
import net.minecraft.tileentity.TileEntityPiston;
import net.minecraft.tileentity.TileEntityShulkerBox;
import net.minecraft.util.datafix.fixes.AddBedTileEntity;
import net.minecraft.util.datafix.fixes.ArmorStandSilent;
import net.minecraft.util.datafix.fixes.BannerItemColor;
import net.minecraft.util.datafix.fixes.BedItemColor;
import net.minecraft.util.datafix.fixes.BookPagesStrictJSON;
import net.minecraft.util.datafix.fixes.CookedFishIDTypo;
import net.minecraft.util.datafix.fixes.ElderGuardianSplit;
import net.minecraft.util.datafix.fixes.EntityArmorAndHeld;
import net.minecraft.util.datafix.fixes.EntityHealth;
import net.minecraft.util.datafix.fixes.EntityId;
import net.minecraft.util.datafix.fixes.ForceVBOOn;
import net.minecraft.util.datafix.fixes.HorseSaddle;
import net.minecraft.util.datafix.fixes.HorseSplit;
import net.minecraft.util.datafix.fixes.ItemIntIDToString;
import net.minecraft.util.datafix.fixes.MinecartEntityTypes;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguage;
import net.minecraft.util.datafix.fixes.PaintingDirection;
import net.minecraft.util.datafix.fixes.PotionItems;
import net.minecraft.util.datafix.fixes.PotionWater;
import net.minecraft.util.datafix.fixes.RedundantChanceTags;
import net.minecraft.util.datafix.fixes.RidingToPassengers;
import net.minecraft.util.datafix.fixes.ShulkerBoxEntityColor;
import net.minecraft.util.datafix.fixes.ShulkerBoxItemColor;
import net.minecraft.util.datafix.fixes.ShulkerBoxTileColor;
import net.minecraft.util.datafix.fixes.SignStrictJSON;
import net.minecraft.util.datafix.fixes.SkeletonSplit;
import net.minecraft.util.datafix.fixes.SpawnEggNames;
import net.minecraft.util.datafix.fixes.SpawnerEntityTypes;
import net.minecraft.util.datafix.fixes.StringToUUID;
import net.minecraft.util.datafix.fixes.TileEntityId;
import net.minecraft.util.datafix.fixes.TotemItemRename;
import net.minecraft.util.datafix.fixes.ZombieProfToType;
import net.minecraft.util.datafix.fixes.ZombieSplit;
import net.minecraft.world.chunk.storage.AnvilChunkLoader;
import net.minecraft.world.gen.structure.template.Template;
import net.minecraft.world.storage.WorldInfo;

public class DataFixesManager {
   private static void registerFixes(DataFixer var0) {
      ☃.registerFix(FixTypes.ENTITY, new EntityArmorAndHeld());
      ☃.registerFix(FixTypes.BLOCK_ENTITY, new SignStrictJSON());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new ItemIntIDToString());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new PotionItems());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new SpawnEggNames());
      ☃.registerFix(FixTypes.ENTITY, new MinecartEntityTypes());
      ☃.registerFix(FixTypes.BLOCK_ENTITY, new SpawnerEntityTypes());
      ☃.registerFix(FixTypes.ENTITY, new StringToUUID());
      ☃.registerFix(FixTypes.ENTITY, new EntityHealth());
      ☃.registerFix(FixTypes.ENTITY, new HorseSaddle());
      ☃.registerFix(FixTypes.ENTITY, new PaintingDirection());
      ☃.registerFix(FixTypes.ENTITY, new RedundantChanceTags());
      ☃.registerFix(FixTypes.ENTITY, new RidingToPassengers());
      ☃.registerFix(FixTypes.ENTITY, new ArmorStandSilent());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new BookPagesStrictJSON());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new CookedFishIDTypo());
      ☃.registerFix(FixTypes.ENTITY, new ZombieProfToType());
      ☃.registerFix(FixTypes.OPTIONS, new ForceVBOOn());
      ☃.registerFix(FixTypes.ENTITY, new ElderGuardianSplit());
      ☃.registerFix(FixTypes.ENTITY, new SkeletonSplit());
      ☃.registerFix(FixTypes.ENTITY, new ZombieSplit());
      ☃.registerFix(FixTypes.ENTITY, new HorseSplit());
      ☃.registerFix(FixTypes.BLOCK_ENTITY, new TileEntityId());
      ☃.registerFix(FixTypes.ENTITY, new EntityId());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new BannerItemColor());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new PotionWater());
      ☃.registerFix(FixTypes.ENTITY, new ShulkerBoxEntityColor());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new ShulkerBoxItemColor());
      ☃.registerFix(FixTypes.BLOCK_ENTITY, new ShulkerBoxTileColor());
      ☃.registerFix(FixTypes.OPTIONS, new OptionsLowerCaseLanguage());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new TotemItemRename());
      ☃.registerFix(FixTypes.CHUNK, new AddBedTileEntity());
      ☃.registerFix(FixTypes.ITEM_INSTANCE, new BedItemColor());
   }

   public static DataFixer createFixer() {
      DataFixer ☃ = new DataFixer(1343);
      WorldInfo.registerFixes(☃);
      EntityPlayerMP.registerFixesPlayerMP(☃);
      EntityPlayer.registerFixesPlayer(☃);
      AnvilChunkLoader.registerFixes(☃);
      ItemStack.registerFixes(☃);
      Template.registerFixes(☃);
      Entity.registerFixes(☃);
      EntityArmorStand.registerFixesArmorStand(☃);
      EntityArrow.registerFixesArrow(☃);
      EntityBat.registerFixesBat(☃);
      EntityBlaze.registerFixesBlaze(☃);
      EntityCaveSpider.registerFixesCaveSpider(☃);
      EntityChicken.registerFixesChicken(☃);
      EntityCow.registerFixesCow(☃);
      EntityCreeper.registerFixesCreeper(☃);
      EntityDonkey.registerFixesDonkey(☃);
      EntityDragonFireball.registerFixesDragonFireball(☃);
      EntityElderGuardian.registerFixesElderGuardian(☃);
      EntityDragon.registerFixesDragon(☃);
      EntityEnderman.registerFixesEnderman(☃);
      EntityEndermite.registerFixesEndermite(☃);
      EntityEvoker.registerFixesEvoker(☃);
      EntityFallingBlock.registerFixesFallingBlock(☃);
      EntityFireworkRocket.registerFixesFireworkRocket(☃);
      EntityGhast.registerFixesGhast(☃);
      EntityGiantZombie.registerFixesGiantZombie(☃);
      EntityGuardian.registerFixesGuardian(☃);
      EntityHorse.registerFixesHorse(☃);
      EntityHusk.registerFixesHusk(☃);
      EntityItem.registerFixesItem(☃);
      EntityItemFrame.registerFixesItemFrame(☃);
      EntityLargeFireball.registerFixesLargeFireball(☃);
      EntityMagmaCube.registerFixesMagmaCube(☃);
      EntityMinecartChest.registerFixesMinecartChest(☃);
      EntityMinecartCommandBlock.registerFixesMinecartCommand(☃);
      EntityMinecartFurnace.registerFixesMinecartFurnace(☃);
      EntityMinecartHopper.registerFixesMinecartHopper(☃);
      EntityMinecartEmpty.registerFixesMinecartEmpty(☃);
      EntityMinecartMobSpawner.registerFixesMinecartMobSpawner(☃);
      EntityMinecartTNT.registerFixesMinecartTNT(☃);
      EntityMule.registerFixesMule(☃);
      EntityMooshroom.registerFixesMooshroom(☃);
      EntityOcelot.registerFixesOcelot(☃);
      EntityPig.registerFixesPig(☃);
      EntityPigZombie.registerFixesPigZombie(☃);
      EntityRabbit.registerFixesRabbit(☃);
      EntitySheep.registerFixesSheep(☃);
      EntityShulker.registerFixesShulker(☃);
      EntitySilverfish.registerFixesSilverfish(☃);
      EntitySkeleton.registerFixesSkeleton(☃);
      EntitySkeletonHorse.registerFixesSkeletonHorse(☃);
      EntitySlime.registerFixesSlime(☃);
      EntitySmallFireball.registerFixesSmallFireball(☃);
      EntitySnowman.registerFixesSnowman(☃);
      EntitySnowball.registerFixesSnowball(☃);
      EntitySpectralArrow.registerFixesSpectralArrow(☃);
      EntitySpider.registerFixesSpider(☃);
      EntitySquid.registerFixesSquid(☃);
      EntityStray.registerFixesStray(☃);
      EntityEgg.registerFixesEgg(☃);
      EntityEnderPearl.registerFixesEnderPearl(☃);
      EntityExpBottle.registerFixesExpBottle(☃);
      EntityPotion.registerFixesPotion(☃);
      EntityTippedArrow.registerFixesTippedArrow(☃);
      EntityVex.registerFixesVex(☃);
      EntityVillager.registerFixesVillager(☃);
      EntityIronGolem.registerFixesIronGolem(☃);
      EntityVindicator.registerFixesVindicator(☃);
      EntityWitch.registerFixesWitch(☃);
      EntityWither.registerFixesWither(☃);
      EntityWitherSkeleton.registerFixesWitherSkeleton(☃);
      EntityWitherSkull.registerFixesWitherSkull(☃);
      EntityWolf.registerFixesWolf(☃);
      EntityZombie.registerFixesZombie(☃);
      EntityZombieHorse.registerFixesZombieHorse(☃);
      EntityZombieVillager.registerFixesZombieVillager(☃);
      TileEntityPiston.registerFixesPiston(☃);
      TileEntityFlowerPot.registerFixesFlowerPot(☃);
      TileEntityFurnace.registerFixesFurnace(☃);
      TileEntityChest.registerFixesChest(☃);
      TileEntityDispenser.registerFixes(☃);
      TileEntityDropper.registerFixesDropper(☃);
      TileEntityBrewingStand.registerFixesBrewingStand(☃);
      TileEntityHopper.registerFixesHopper(☃);
      BlockJukebox.registerFixesJukebox(☃);
      TileEntityMobSpawner.registerFixesMobSpawner(☃);
      TileEntityShulkerBox.registerFixesShulkerBox(☃);
      registerFixes(☃);
      return ☃;
   }

   public static NBTTagCompound processItemStack(IDataFixer var0, NBTTagCompound var1, int var2, String var3) {
      if (☃.hasKey(☃, 10)) {
         ☃.setTag(☃, ☃.process(FixTypes.ITEM_INSTANCE, ☃.getCompoundTag(☃), ☃));
      }

      return ☃;
   }

   public static NBTTagCompound processInventory(IDataFixer var0, NBTTagCompound var1, int var2, String var3) {
      if (☃.hasKey(☃, 9)) {
         NBTTagList ☃ = ☃.getTagList(☃, 10);

         for (int ☃x = 0; ☃x < ☃.tagCount(); ☃x++) {
            ☃.set(☃x, ☃.process(FixTypes.ITEM_INSTANCE, ☃.getCompoundTagAt(☃x), ☃));
         }
      }

      return ☃;
   }
}
